USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS DBTROLE;
GRANT ROLE DBTROLE TO ROLE ACCOUNTADMIN;

GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE DBTROLE;

CREATE USER IF NOT EXISTS dbtuser
  PASSWORD='dbtuser'
  LOGIN_NAME='dbtuser'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=DBTROLE
  DEFAULT_NAMESPACE='HR_ANALYTICS'
  TYPE = LEGACY_SERVICE

  GRANT ROLE DBTROLE TO USER dbtuser;

CREATE DATABASE IF NOT EXISTS HR_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS HR_ANALYTICS.STAGING;

GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE DBTROLE;
GRANT ALL ON DATABASE HR_ANALYTICS TO ROLE DBTROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE HR_ANALYTICS TO ROLE DBTROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE HR_ANALYTICS TO ROLE DBTROLE;
GRANT ALL ON ALL TABLES IN SCHEMA HR_ANALYTICS.STAGING TO ROLE DBTROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA HR_ANALYTICS.STAGING TO ROLE DBTROLE;

select current_user()

